GET https://uslbc8e6pk.execute-api.eu-west-1.amazonaws.com/prod/spaces?id=5a79c69b-31d7-4ffe-8546-0587ebd923d4
###

POST https://uslbc8e6pk.execute-api.eu-west-1.amazonaws.com/prod/spaces
content-type: application/json

{
  "location" : "Paris",
}
###
